package com.spring.springboot.dao;

import com.spring.springboot.entity.XtFun;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
@Mapper
public interface XtFunMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xt_fun
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("id") Integer id, @Param("funcName") String funcName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xt_fun
     *
     * @mbg.generated
     */
    int insert(XtFun record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xt_fun
     *
     * @mbg.generated
     */
    XtFun selectByPrimaryKey(@Param("id") Integer id, @Param("funcName") String funcName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xt_fun
     *
     * @mbg.generated
     */
    List<XtFun> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xt_fun
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(XtFun record);


    XtFun selectById(@Param("id") Integer id);
}