package com.spring.springboot.entity;

import java.io.Serializable;
import java.util.Date;

public class XtFun implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_fun.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_fun.func_name
     *
     * @mbg.generated
     */
    private String funcName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_fun.func_desc
     *
     * @mbg.generated
     */
    private String funcDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_fun.delete_flag
     *
     * @mbg.generated
     */
    private String deleteFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_fun.filesName
     *
     * @mbg.generated
     */
    private String filesname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_fun.filetype
     *
     * @mbg.generated
     */
    private String filetype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_fun.fileversion
     *
     * @mbg.generated
     */
    private String fileversion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_fun.filedate
     *
     * @mbg.generated
     */
    private Date filedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_fun.explain
     *
     * @mbg.generated
     */
    private String explain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_fun.filehandle
     *
     * @mbg.generated
     */
    private Integer filehandle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_fun.operdate
     *
     * @mbg.generated
     */
    private Date operdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_fun.operate
     *
     * @mbg.generated
     */
    private String operate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_fun.group_code
     *
     * @mbg.generated
     */
    private String groupCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xt_fun
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_fun.id
     *
     * @return the value of xt_fun.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_fun.id
     *
     * @param id the value for xt_fun.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_fun.func_name
     *
     * @return the value of xt_fun.func_name
     *
     * @mbg.generated
     */
    public String getFuncName() {
        return funcName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_fun.func_name
     *
     * @param funcName the value for xt_fun.func_name
     *
     * @mbg.generated
     */
    public void setFuncName(String funcName) {
        this.funcName = funcName == null ? null : funcName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_fun.func_desc
     *
     * @return the value of xt_fun.func_desc
     *
     * @mbg.generated
     */
    public String getFuncDesc() {
        return funcDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_fun.func_desc
     *
     * @param funcDesc the value for xt_fun.func_desc
     *
     * @mbg.generated
     */
    public void setFuncDesc(String funcDesc) {
        this.funcDesc = funcDesc == null ? null : funcDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_fun.delete_flag
     *
     * @return the value of xt_fun.delete_flag
     *
     * @mbg.generated
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_fun.delete_flag
     *
     * @param deleteFlag the value for xt_fun.delete_flag
     *
     * @mbg.generated
     */
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag == null ? null : deleteFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_fun.filesName
     *
     * @return the value of xt_fun.filesName
     *
     * @mbg.generated
     */
    public String getFilesname() {
        return filesname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_fun.filesName
     *
     * @param filesname the value for xt_fun.filesName
     *
     * @mbg.generated
     */
    public void setFilesname(String filesname) {
        this.filesname = filesname == null ? null : filesname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_fun.filetype
     *
     * @return the value of xt_fun.filetype
     *
     * @mbg.generated
     */
    public String getFiletype() {
        return filetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_fun.filetype
     *
     * @param filetype the value for xt_fun.filetype
     *
     * @mbg.generated
     */
    public void setFiletype(String filetype) {
        this.filetype = filetype == null ? null : filetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_fun.fileversion
     *
     * @return the value of xt_fun.fileversion
     *
     * @mbg.generated
     */
    public String getFileversion() {
        return fileversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_fun.fileversion
     *
     * @param fileversion the value for xt_fun.fileversion
     *
     * @mbg.generated
     */
    public void setFileversion(String fileversion) {
        this.fileversion = fileversion == null ? null : fileversion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_fun.filedate
     *
     * @return the value of xt_fun.filedate
     *
     * @mbg.generated
     */
    public Date getFiledate() {
        return filedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_fun.filedate
     *
     * @param filedate the value for xt_fun.filedate
     *
     * @mbg.generated
     */
    public void setFiledate(Date filedate) {
        this.filedate = filedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_fun.explain
     *
     * @return the value of xt_fun.explain
     *
     * @mbg.generated
     */
    public String getExplain() {
        return explain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_fun.explain
     *
     * @param explain the value for xt_fun.explain
     *
     * @mbg.generated
     */
    public void setExplain(String explain) {
        this.explain = explain == null ? null : explain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_fun.filehandle
     *
     * @return the value of xt_fun.filehandle
     *
     * @mbg.generated
     */
    public Integer getFilehandle() {
        return filehandle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_fun.filehandle
     *
     * @param filehandle the value for xt_fun.filehandle
     *
     * @mbg.generated
     */
    public void setFilehandle(Integer filehandle) {
        this.filehandle = filehandle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_fun.operdate
     *
     * @return the value of xt_fun.operdate
     *
     * @mbg.generated
     */
    public Date getOperdate() {
        return operdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_fun.operdate
     *
     * @param operdate the value for xt_fun.operdate
     *
     * @mbg.generated
     */
    public void setOperdate(Date operdate) {
        this.operdate = operdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_fun.operate
     *
     * @return the value of xt_fun.operate
     *
     * @mbg.generated
     */
    public String getOperate() {
        return operate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_fun.operate
     *
     * @param operate the value for xt_fun.operate
     *
     * @mbg.generated
     */
    public void setOperate(String operate) {
        this.operate = operate == null ? null : operate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_fun.group_code
     *
     * @return the value of xt_fun.group_code
     *
     * @mbg.generated
     */
    public String getGroupCode() {
        return groupCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_fun.group_code
     *
     * @param groupCode the value for xt_fun.group_code
     *
     * @mbg.generated
     */
    public void setGroupCode(String groupCode) {
        this.groupCode = groupCode == null ? null : groupCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xt_fun
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", funcName=").append(funcName);
        sb.append(", funcDesc=").append(funcDesc);
        sb.append(", deleteFlag=").append(deleteFlag);
        sb.append(", filesname=").append(filesname);
        sb.append(", filetype=").append(filetype);
        sb.append(", fileversion=").append(fileversion);
        sb.append(", filedate=").append(filedate);
        sb.append(", explain=").append(explain);
        sb.append(", filehandle=").append(filehandle);
        sb.append(", operdate=").append(operdate);
        sb.append(", operate=").append(operate);
        sb.append(", groupCode=").append(groupCode);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}