package com.spring.springboot.entity;

import java.io.Serializable;

public class XtUser implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_user.user_mi
     *
     * @mbg.generated
     */
    private String userMi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_user.pass_word
     *
     * @mbg.generated
     */
    private String passWord;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_user.delete_flag
     *
     * @mbg.generated
     */
    private String deleteFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_user.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_user.sex
     *
     * @mbg.generated
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_user.paper_type
     *
     * @mbg.generated
     */
    private String paperType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_user.social_no
     *
     * @mbg.generated
     */
    private String socialNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_user.tel
     *
     * @mbg.generated
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_user.e_mail
     *
     * @mbg.generated
     */
    private String eMail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_user.home_address
     *
     * @mbg.generated
     */
    private String homeAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_user.exec_unit
     *
     * @mbg.generated
     */
    private String execUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xt_user
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_user.user_mi
     *
     * @return the value of xt_user.user_mi
     *
     * @mbg.generated
     */
    public String getUserMi() {
        return userMi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_user.user_mi
     *
     * @param userMi the value for xt_user.user_mi
     *
     * @mbg.generated
     */
    public void setUserMi(String userMi) {
        this.userMi = userMi == null ? null : userMi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_user.pass_word
     *
     * @return the value of xt_user.pass_word
     *
     * @mbg.generated
     */
    public String getPassWord() {
        return passWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_user.pass_word
     *
     * @param passWord the value for xt_user.pass_word
     *
     * @mbg.generated
     */
    public void setPassWord(String passWord) {
        this.passWord = passWord == null ? null : passWord.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_user.delete_flag
     *
     * @return the value of xt_user.delete_flag
     *
     * @mbg.generated
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_user.delete_flag
     *
     * @param deleteFlag the value for xt_user.delete_flag
     *
     * @mbg.generated
     */
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag == null ? null : deleteFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_user.name
     *
     * @return the value of xt_user.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_user.name
     *
     * @param name the value for xt_user.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_user.sex
     *
     * @return the value of xt_user.sex
     *
     * @mbg.generated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_user.sex
     *
     * @param sex the value for xt_user.sex
     *
     * @mbg.generated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_user.paper_type
     *
     * @return the value of xt_user.paper_type
     *
     * @mbg.generated
     */
    public String getPaperType() {
        return paperType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_user.paper_type
     *
     * @param paperType the value for xt_user.paper_type
     *
     * @mbg.generated
     */
    public void setPaperType(String paperType) {
        this.paperType = paperType == null ? null : paperType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_user.social_no
     *
     * @return the value of xt_user.social_no
     *
     * @mbg.generated
     */
    public String getSocialNo() {
        return socialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_user.social_no
     *
     * @param socialNo the value for xt_user.social_no
     *
     * @mbg.generated
     */
    public void setSocialNo(String socialNo) {
        this.socialNo = socialNo == null ? null : socialNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_user.tel
     *
     * @return the value of xt_user.tel
     *
     * @mbg.generated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_user.tel
     *
     * @param tel the value for xt_user.tel
     *
     * @mbg.generated
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_user.e_mail
     *
     * @return the value of xt_user.e_mail
     *
     * @mbg.generated
     */
    public String geteMail() {
        return eMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_user.e_mail
     *
     * @param eMail the value for xt_user.e_mail
     *
     * @mbg.generated
     */
    public void seteMail(String eMail) {
        this.eMail = eMail == null ? null : eMail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_user.home_address
     *
     * @return the value of xt_user.home_address
     *
     * @mbg.generated
     */
    public String getHomeAddress() {
        return homeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_user.home_address
     *
     * @param homeAddress the value for xt_user.home_address
     *
     * @mbg.generated
     */
    public void setHomeAddress(String homeAddress) {
        this.homeAddress = homeAddress == null ? null : homeAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_user.exec_unit
     *
     * @return the value of xt_user.exec_unit
     *
     * @mbg.generated
     */
    public String getExecUnit() {
        return execUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_user.exec_unit
     *
     * @param execUnit the value for xt_user.exec_unit
     *
     * @mbg.generated
     */
    public void setExecUnit(String execUnit) {
        this.execUnit = execUnit == null ? null : execUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xt_user
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userMi=").append(userMi);
        sb.append(", passWord=").append(passWord);
        sb.append(", deleteFlag=").append(deleteFlag);
        sb.append(", name=").append(name);
        sb.append(", sex=").append(sex);
        sb.append(", paperType=").append(paperType);
        sb.append(", socialNo=").append(socialNo);
        sb.append(", tel=").append(tel);
        sb.append(", eMail=").append(eMail);
        sb.append(", homeAddress=").append(homeAddress);
        sb.append(", execUnit=").append(execUnit);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}