package com.spring.springboot.entity;

import java.io.Serializable;

public class XtUserGroup implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_user_group.user_mi
     *
     * @mbg.generated
     */
    private String userMi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_user_group.func_name
     *
     * @mbg.generated
     */
    private String funcName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xt_user_group
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_user_group.user_mi
     *
     * @return the value of xt_user_group.user_mi
     *
     * @mbg.generated
     */
    public String getUserMi() {
        return userMi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_user_group.user_mi
     *
     * @param userMi the value for xt_user_group.user_mi
     *
     * @mbg.generated
     */
    public void setUserMi(String userMi) {
        this.userMi = userMi == null ? null : userMi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_user_group.func_name
     *
     * @return the value of xt_user_group.func_name
     *
     * @mbg.generated
     */
    public String getFuncName() {
        return funcName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_user_group.func_name
     *
     * @param funcName the value for xt_user_group.func_name
     *
     * @mbg.generated
     */
    public void setFuncName(String funcName) {
        this.funcName = funcName == null ? null : funcName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xt_user_group
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userMi=").append(userMi);
        sb.append(", funcName=").append(funcName);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}